---
# We create the consul group
- name: accounts | creating consul group
  group:
    name: "{{ consul_user_info.group }}"
    state: present
  become: true

# We create the consul user and add it to the consul group
- name: accounts | creating consul user
  user:
    createhome: false
    group: "{{ consul_user_info.group }}"
    name: "{{ consul_user_info.user }}"
    shell: /bin/false
    system: true
  become: true
