---
- name: debian | Updating Apt Cache
  apt:
    update_cache: true
  become: true

- name: debian | installing dependencies
  apt:
    name:
      - dnsutils
      - jq
      - tree
      - unzip
      - uuid-runtime
    state: present
  become: true
  register: result
  until: result is successful
