---
- name: debian | Updating Apt Cache
  apt:
    update_cache: true
  become: true

- name: debian | installing dependencies
  apt:
    name: ["jq", "tree", "unzip", "uuid-runtime"]
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | installing add'l dependencies (Debian)
  apt:
    name: ["dnsutils"]
    state: present
  become: true
  when: ansible_distribution == "Debian"
  register: result
  until: result is successful
