---
- name: debian | Updating Apt Cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: debian | installing dependencies
  ansible.builtin.apt:
    name:
      - cron
      - dnsutils
      - jq
      - python3-pip
      - python3-requests
      - python3-setuptools
      - tree
      - unzip
      - uuid-runtime
    state: present
  become: true
  register: result
  until: result is successful
