---
- name: dnsmasq | installing dnsmasq
  ansible.builtin.package:
    name: dnsmasq
    state: present
  become: true
  register: result
  until: result is successful

- name: dnsmasq | ensuring dnsmasq service is enabled
  ansible.builtin.service:
    name: dnsmasq
    enabled: true
  become: true

- name: dnsmasq | configuring dnsmasq to resolv consul dns
  ansible.builtin.template:
    src: etc/dnsmasq.d/10-consul.j2
    dest: /etc/dnsmasq.d/10-consul
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify:
    - restart dnsmasq
