---
- name: install | check if consul binary is installed
  stat:
    path: "{{ consul_bin_path + '/consul' }}"
  register: consul_binary_exists
  ignore_errors: true
  become: true

- name: install | try to determine current consul version # noqa 306
  shell: "{{ consul_bin_path + '/consul version' }} | head -1 | cut -d 'v' -f2"
  register: consul_version_installed
  changed_when: false
  when:
    - consul_upgrade|bool
    - consul_binary_exists.stat.exists

- name: install | backup current binary as fallback # noqa 305
  shell: "mv {{ consul_bin_path + '/consul' }} {{ consul_bin_path + '/consul_backup' }}"
  register: consul_binary_backup
  become: true
  when:
    - consul_upgrade|bool
    - consul_binary_exists.stat.exists
    - consul_version_installed.stdout < consul_version
    - not ansible_check_mode

- name: install | download and extract consul
  unarchive:
    src: "{{ consul_dl_url + '/' + consul_dl_file }}"
    dest: "{{ consul_bin_path }}"
    remote_src: True
    creates: "{{ consul_bin_path + '/consul' }}"
    dest: "{{ consul_bin_path+'/' }}"
    group: "{{ consul_user_info.group }}"
    owner: "{{ consul_user_info.user }}"
    remote_src: true
    src: "{{ 'https://releases.hashicorp.com/consul/'+consul_version|string+'/consul_'+consul_version|string+'_linux_amd64.zip' }}"
  become: true
  register: consul_download_extract
  notify:
    - restart consul
  when: not ansible_check_mode

- name: install | restoring former binary as upgrade failed # noqa 305
  shell: "mv {{ consul_bin_path + '/consul_backup' }} {{ consul_bin_path + '/consul' }}"
  become: true
  register: consul_binary_restore
  notify:
    - restart consul
  when:
    - consul_download_extract is failed
    - consul_binary_backup is successful
    - not ansible_check_mode

- name: install | remove not required binary backup
  file:
    path: "{{ consul_bin_path + '/consul_backup' }}"
    state: absent
  when: consul_download_extract is successful

- name: install | ensure binary ownership and mode
  file:
    path: "{{ consul_bin_path + '/consul' }}"
    owner: "{{ consul_bin_owner }}"
    group: "{{ consul_bin_group }}"
    mode: "{{ consul_bin_mode }}"
  become: true
  notify:
    - restart consul
  when: not ansible_check_mode
