---
# tasks file for ansible-consul

- name: Apply Debian tasks
  ansible.builtin.import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: Apply RHEL tasks
  ansible.builtin.import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Manage accounts
  ansible.builtin.import_tasks: accounts.yml

- name: Install Consul
  ansible.builtin.import_tasks: install.yml

- name: Configure Consul
  ansible.builtin.import_tasks: config.yml

- name: Manage Consul services
  ansible.builtin.import_tasks: services.yml

- name: Manage Consul ACLs
  ansible.builtin.import_tasks: acl.yml
  when:
    - consul_acl is defined
    - consul_configuration.datacenter == consul_configuration.primary_datacenter

- name: Install DNSMasq
  ansible.builtin.import_tasks: dnsmasq.yml
  when:
    - consul_enable_dnsmasq is defined
    - consul_enable_dnsmasq|bool
