---
# tasks file for ansible-consul

- import_tasks: debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: accounts.yml

- import_tasks: install.yml

- import_tasks: config.yml

- import_tasks: services.yml

- import_tasks: app_services.yml
  when:
    - consul_services is defined
    - consul_services

- import_tasks: acl.yml
  when:
    - consul_acl is defined
    - consul_configuration.datacenter == consul_configuration.primary_datacenter

- import_tasks: dnsmasq.yml
  when:
    - consul_enable_dnsmasq is defined
    - consul_enable_dnsmasq|bool
