---
- name: redhat | installing epel repo (RedHat)
  yum:
    name: epel-release
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | installing dependencies
  yum:
    name: ["python-devel", "python-pip"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | installing add'l dependencies (Fedora)
  package:
    name:
      - jq
      - tree
      - unzip
    state: present
  become: true
  register: result
  until: result is successful
