---
# handlers file for ansible-consul
- name: reload systemd
  ansible.builtin.systemd:
    name: consul
    daemon_reload: yes
  become: true

- name: reload consul
  ansible.builtin.service:
    name: consul
    state: reloaded
  become: true

- name: restart consul
  ansible.builtin.service:
    name: consul
    state: restarted
  become: true

- name: start consul
  ansible.builtin.service:
    name: consul
    state: started
  become: true

- name: stop consul
  ansible.builtin.service:
    name: consul
    state: stopped
  become: true

- name: restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
  become: true
