---
# handlers file for ansible-consul
- name: reload systemd
  systemd:
    name: consul
    daemon_reload: yes
  become: true
  when: not ansible_check_mode

- name: reload consul
  service:
    name: consul
    state: reloaded
  become: true
  when: not ansible_check_mode

- name: restart consul
  service:
    name: consul
    state: restarted
  become: true
  when: not ansible_check_mode

- name: start consul
  service:
    name: consul
    state: started
  become: true
  when: not ansible_check_mode

- name: stop consul
  service:
    name: consul
    state: stopped
  become: true
  when: not ansible_check_mode

- name: restart dnsmasq
  service:
    name: dnsmasq
    state: restarted
  become: true
  when: not ansible_check_mode
