---
- name: Converge
  hosts: all
  tasks:
    - name: Applying ansible-bootstrap-python role
      import_role:
        name: ansible-bootstrap-python

    - name: Include ansible-consul
      include_role:
        name: ansible-consul
